### ISSUE TITLE
Publish on PyPI?

### ISSUE THREAD

**Issue by cloneofghosts** [Pirate-Weather/pirate-weather-python#3]
@alexander0042 Not sure if this is something you want to do but I could publish this library to PyPI if you'd like. I already have an account setup on PyPI and I setup the [GitHub action](https://github.com/cloneofghosts/python-pirate-weather/blob/master/.github/workflows/release.yml) on my forecastio fork so it should be pretty straightforward for me to publish this.

**Comment by cloneofghosts** [comment]
@alexander0042 I know this isn't super urgent but if you'd like the project to be published on PyPI I can continue the setup I started in this branch: https://github.com/Pirate-Weather/pirate-weather-python/tree/pypi. There are some lint errors but it mainly seems to be missing docstrings which we'll need to fix before publishing.

The name will also need to be changed as there is already a library on pypi with the same name so it'll need to be changed.

Not a huge deal if you'd prefer to not publish this on PyPI though as I'll just delete the branch I was working on.

**Comment by alexander0042** [comment]
I love this idea in the medium term! The code is already there, so very doable, although we'd have to figure out how to go about getting on there, 

Name is a little irritating, but probably just "pirateweather" would be best! Not sure if it has to be the same name as the repo, but hopefully not

**Comment by cloneofghosts** [comment]
> I love this idea in the medium term! The code is already there, so very doable, although we'd have to figure out how to go about getting on there,

It's not too complicated to setup. I basically followed [this guide](https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/) to get the GitHub action workflow to work for my fork. I didn't bother setting up `testpypi` on my fork but if you feel it might be useful then feel free. 

> Name is a little irritating, but probably just "pirateweather" would be best! Not sure if it has to be the same name as the repo, but hopefully not

Nope, it can be different. All that matters is that the name in setup.py and the name on PyPI are the same. My branch is called python-pirate-weather on GitHub but is caleld python-pirateweather on PyPI.

**Comment by cloneofghosts** [comment]
I setup the workflow but it's having permission issues. I'll see if I can figure anything out.

**Comment by cloneofghosts** [comment]
@alexander0042 It took me way way too long to figure out what the issue was but I got it fixed and the library is now on PyPi here: https://pypi.org/project/pirateweather/
